import{a as L,i as n,S as h}from"./assets/vendor-5401a4b0.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const i of t)if(i.type==="childList")for(const g of i.addedNodes)g.tagName==="LINK"&&g.rel==="modulepreload"&&d(g)}).observe(document,{childList:!0,subtree:!0});function e(t){const i={};return t.integrity&&(i.integrity=t.integrity),t.referrerPolicy&&(i.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?i.credentials="include":t.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function d(t){if(t.ep)return;t.ep=!0;const i=e(t);fetch(t.href,i)}})();let f=async s=>await L.get(`https://pixabay.com/api/?${s}`).then(r=>r.data);function y(s){return s.reduce((r,e)=>r+=`<div class="image-box">
                        <a href="${e.largeImageURL}">
                       <img class="image" src=${e.webformatURL} alt="${e.tags}"  height="200" width="360"/>
                          <div class="image-discr">
                            <p class="text"><span class="image-title">Likes</span>${e.likes}</p>
                            <p class="text"><span class="image-title">Views</span>${e.views}</p>
                            <p class="text"><span class="image-title">Comments</span>${e.comments}</p>
                            <p class="text"><span class="image-title">Downloads</span>${e.downloads}</p> 
                          </div>
                        </a>
                    </div>`,"")}const l="/goit-js-hw-12/assets/icon-close-6c427745.svg",a=new URLSearchParams({key:"4348225-c90d49c3185e1d6dd0df9aa80",q:"",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:1}),c=document.querySelector(".loader"),m=document.querySelector(".loader-more"),o=document.querySelector(".gallery"),u=document.querySelector(".form"),p=document.querySelector(".btn-load-more");u.addEventListener("submit",s=>{s.preventDefault();const r=s.target.elements.input.value.trim();r?(o.innerHTML="",c.classList.remove("invisible"),a.set("q",r),a.set("page",1),f(a).then(async e=>{e.hits.length===0?(c.classList.add("invisible"),o.innerHTML="",n.error({position:"topRight",maxWidth:"380px",progressBar:!1,iconUrl:l,transitionIn:"fadeInLeft",message:"Sorry, there are no images matching your search query. Please try again!"})):(c.classList.add("invisible"),o.innerHTML=await y(e.hits),a.set("page",Number(a.get("page"))+1),new h(".gallery a",{captionsData:"alt",captionDelay:250}).refresh(),e.hits.length<e.total&&p.classList.remove("invisible"))}).catch(e=>{n.error({position:"topRight",maxWidth:"380px",progressBar:!1,iconUrl:l,transitionIn:"fadeInLeft",message:`Error:${e} `})})):(c.classList.add("invisible"),o.innerHTML="",n.show({progressBar:!1,position:"topRight",maxWidth:"380px",iconUrl:l,transitionIn:"fadeInLeft",message:"Put the request!"})),u.reset()});p.addEventListener("click",b);function b(){p.classList.add("invisible"),m.classList.remove("invisible"),f(a).then(s=>{if(s.hits.length===0)m.classList.add("invisible"),o.innerHTML="",n.error({position:"topRight",maxWidth:"380px",progressBar:!1,iconUrl:l,transitionIn:"fadeInLeft",message:"Sorry, there are no images matching your search query. Please try again!"});else{m.classList.add("invisible"),o.insertAdjacentHTML("beforeend",y(s.hits)),a.set("page",Number(a.get("page"))+1),new h(".gallery a",{captionsData:"alt",captionDelay:250}).refresh();const e=document.querySelector(".image-box").getBoundingClientRect().height;window.scrollBy({top:e*2+72,behavior:"smooth"}),(Number(a.get("page"))-1)*Number(a.get("per_page"))<s.total?p.classList.remove("invisible"):n.show({position:"topRight",maxWidth:"380px",progressBar:!1,iconUrl:l,transitionIn:"fadeInLeft",message:"We're sorry, but you've reached the end of search results."})}})}
//# sourceMappingURL=commonHelpers.js.map
