import{i as c,S as u}from"./assets/vendor-5b791d57.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();let m=i=>fetch(`https://pixabay.com/api/?${i}`).then(s=>s.ok?s.json():new Error(`Error: ${s.status}`));function g(i){return i.reduce((s,t)=>s+=`<div class="image-box">
                        <a href="${t.largeImageURL}">
                       <img class="image" src=${t.webformatURL} alt="${t.tags}"  height="200" width="360"/>
                          <div class="image-discr">
                            <p class="text"><span class="image-title">Likes</span>${t.likes}</p>
                            <p class="text"><span class="image-title">Views</span>${t.views}</p>
                            <p class="text"><span class="image-title">Comments</span>${t.comments}</p>
                            <p class="text"><span class="image-title">Downloads</span>${t.downloads}</p> 
                          </div>
                        </a>
                    </div>`,"")}const p="/goit-js-hw-11/assets/icon-close-6c427745.svg",d=new URLSearchParams({key:"4348225-c90d49c3185e1d6dd0df9aa80",q:"",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:21}),a=document.querySelector(".loader"),o=document.querySelector(".gallery"),f=document.querySelector(".form");f.addEventListener("submit",i=>{i.preventDefault();const s=i.target.elements.input.value.trim();s?(o.innerHTML="",a.classList.remove("invisible"),d.set("q",s),m(d).then(t=>{t.hits.length===0?(a.classList.add("invisible"),o.innerHTML="",c.error({position:"topRight",maxWidth:"380px",progressBar:!1,iconUrl:p,transitionIn:"fadeInLeft",message:"Sorry, there are no images matching your search query. Please try again!"})):(a.classList.add("invisible"),o.innerHTML=g(t.hits),new u(".gallery a",{captionsData:"alt",captionDelay:250}).refresh())}).catch(t=>{c.error({position:"topRight",maxWidth:"380px",progressBar:!1,iconUrl:p,transitionIn:"fadeInLeft",message:`Error:${t} `})})):(a.classList.add("invisible"),o.innerHTML="",c.show({progressBar:!1,position:"topRight",maxWidth:"380px",iconUrl:p,transitionIn:"fadeInLeft",message:"Put the request!"})),f.reset()});
//# sourceMappingURL=commonHelpers.js.map
